- name: 'deploy borgmatic.service unit files'
  template:
    backup: yes
    dest: '/etc/systemd/system/{{ item }}'
    mode: '0644'
    src: '{{ item }}.j2'
  loop:
    - 'borgmatic.timer'
    - 'borgmatic.service'
  notify:
    - 'daemon-reload'

- name: 'deploy borgmatic-check.service unit files'
  template:
    backup: yes
    dest: '/etc/systemd/system/{{ item }}'
    mode: '0644'
    src: '{{ item }}.j2'
  loop:
    - 'borgmatic-check.timer'
    - 'borgmatic-check.service'
  notify:
    - 'daemon-reload'
  when:
    - 'borgmatic_large_repo'

- name: 'enable and start borgmatic.timer'
  systemd:
    enabled: yes
    name: 'borgmatic.timer'
    state: 'started'

- name: 'enable and start borgmatic-check.timer'
  systemd:
    enabled: yes
    name: 'borgmatic-check.timer'
    state: 'started'
  when:
    - 'borgmatic_large_repo'
